eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: message-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: messageTopic
    consumer:
      group-id: messageId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.chrisbaileydeveloper.messageservice.OrderPlacedEvent

server:
  port: 8084

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans/
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
