spring:
  datasource:
    url: jdbc:postgresql://postgres-stock-check:5432/stock_check_service
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true
