server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/stock-check-service
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
