server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configurations

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka